# Generated by binpac_quickstart
# Dop: Oct 2017

# can we limit how many packets into a connection we bother looking at?

signature dpd_gquic {
	# Let's start with Google's QUIC implementation
	
	ip-proto == udp
	payload /^.{9}Q0(2|3|4)/
	enable "gquic"
}


# I'm not 100% that \x02 will always be set...  ie, \x82 vs just \x80
signature dpd_ietf_draft_quic {
	
	ip-proto == udp
	payload /^(\x80|\x82).{12}\xff\x00\x00(\x01|\x02|\x03|\x05|\x06)/
	enable "quic"
}

