// Generated by binpac_quickstart

#include "GQUIC.h"

#include "Reporter.h"

#include "events.bif.h"

using namespace analyzer::gquic;

GQUIC_Analyzer::GQUIC_Analyzer(Connection* c)

: analyzer::Analyzer("GQUIC", c)

	{
	interp = new binpac::GQUIC::GQUIC_Conn(this);
	
	}

GQUIC_Analyzer::~GQUIC_Analyzer()
	{
	delete interp;
	}

void GQUIC_Analyzer::Done()
	{
	
	Analyzer::Done();
	
	}

void GQUIC_Analyzer::DeliverPacket(int len, const u_char* data,
	 			  bool orig, uint64 seq, const IP_Hdr* ip, int caplen)
	{
	Analyzer::DeliverPacket(len, data, orig, seq, ip, caplen);

	try
		{
		interp->NewData(orig, data, data + len);
		}
	catch ( const binpac::Exception& e )
		{
		ProtocolViolation(fmt("Binpac exception: %s", e.c_msg()));
		}
	}
