// Generated by binpac_quickstart

#include "plugin/Plugin.h"

#include "QUIC.h"
#include "GQUIC.h"

namespace plugin {
namespace Bro_QUIC {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		  AddComponent(new ::analyzer::Component("QUIC",
		             ::analyzer::quic::QUIC_Analyzer::InstantiateAnalyzer));
		  AddComponent(new ::analyzer::Component("GQUIC",
		             ::analyzer::gquic::GQUIC_Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "Bro::QUIC";
		config.description = "QUIC Protocol analyzers";
		return config;
		}
} plugin;

}
}
