# Generated by binpac_quickstart
# Dop: Oct 2017

refine flow QUIC_Flow += {
	function proc_quic_message(msg: QUIC_PDU): bool
		%{
		BifEvent::generate_quic_event(connection()->bro_analyzer(), connection()->bro_analyzer()->Conn(),
					bytestring_to_val(${msg.QH.version}),
					${msg.QH.version_bool}
						);
					
		return true;
		%}
};

refine typeattr QUIC_PDU += &let {
	proc: bool = $context.flow.proc_quic_message(this);
};